import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import { Container, Card, Row, Col, Button } from 'react-bootstrap'

import thumbnail from '../images/thumbnail.jpg'



export default function Home() {
  const cardTab = 
  [
  {title: 'Card Title', text:'Some quick example text to build on the card title and make up the bulk of the cards content.'},
  {title: 'Card Title', text:'Some quick example text to build on the card title and make up the bulk of the cards content.'},
  {title: 'Card Title', text:'Some quick example text to build on the card title and make up the bulk of the cards content.'},
  {title: 'Card Title', text:'Some quick example text to build on the card title and make up the bulk of the cards content.'},
  {title: 'Card Title', text:'Some quick example text to build on the card title and make up the bulk of the cards content.'},
  {title: 'Card Title', text:'Some quick example text to build on the card title and make up the bulk of the cards content.'}
  ];
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="bg-light my-5">
        <h2 className="text-center py-5">Nos annonces spéciaux</h2>
          <Container fluid>
            <Row className="g-2 g-md-3" > 
             {cardTab.map((item, index) =>  <Col xs={12} sm={6} lg={4} xl={3} className="align-items-center" key={index}>
              <Card style={{ width: '16rem' }} className="mx-auto">
            <Image 
            src={thumbnail} 
            alt='image' 
            width={100} 
            height={150} 
            blurDataURL
            />
            <Card.Body>
              <Card.Title>{item.title}</Card.Title>
              <Card.Text>
              {item.text}
              </Card.Text>
            </Card.Body>
          </Card>
              </Col>)}
            </Row>
            <Row>
            <Col className="col-6 col-md-2 mx-auto my-4">
             <Button variant='outline-secondary' size='sm'>Voir plus d&apos;offre</Button>
             </Col>
          </Row>
          </Container>
        </section>
        <section className='bg-white mb-3'>
        <h2 className="text-center py-4">Dernières annonces</h2>
          <Container fluid>
            <Row className='g-2 g-md-3'> 
             {cardTab.map((item, index) =>  <Col xs={12} sm={6} lg={4} xl={3} key={index}>
              <Card style={{ width: '16rem' }} className="mx-auto shadow bg-body rounded">
            <Image 
            src={thumbnail} 
            alt='image' 
            width={100} 
            height={150} 
            blurDataURL
            />
            <Card.Body>
              <Card.Title>{item.title}</Card.Title>
              <Card.Text>
              {item.text}
              </Card.Text>
            </Card.Body>
          </Card>
              </Col>)}
            </Row>
            <Row>
            <Col className="col-6 col-md-2 mx-auto my-4">
             <Button variant='outline-secondary' size='sm'>Voir plus d&apos;offre</Button>
             </Col>
          </Row>
          </Container>
        </section>
       
        <section className="bg-light my-3" style={{height:"300px"}}>
          <h2 className="text-center py-3">Nos partenaires</h2>
          <Container>
            <Row>
              <Col>
                <p className="m-3 text-center">Soyez parmis les premiers à s&apos;inscrire sur notre plateforme, mettre vos annonces et benificier de plusieurs nouvelles fonctionalité gratuites.</p>
              </Col>
              <Col>
               <div><h3>Golden House</h3></div>
               <div><h3>iMMO Immoblier</h3></div>
               <div><h3>chedli Immoblier</h3></div>
              </Col>
            </Row>
          </Container>
        </section>
    </Layout>
  )
}
